version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://dsa_user:securepass@postgres:5432/dsa_automation_dev?schema=public
      JWT_SECRET: dev-secret-key
      PORT: 3000

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dsa_user
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: dsa_automation_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
